### ISSUE TITLE
Separate Tailwind config converting logic from web app

### ISSUE THREAD

**Issue by thaod** [dvkndn/typed-tailwind#7]
Currently the code to convert a Tailwind config to `tw.ts` lies somewhere within the code of web application https://typed-tailwind.com/ . Since web app is only an interface to use the core converting, I suggest to separate the converting code into another place (e.g. `lib/convert-tw.ts`).

With this separation, tests can be written to test only the Tailwind config converting logic. Or develop other interfaces on top of it (e.g. cli).

**Comment by dvkndn** [comment]
@thaod @hadeeb welcome to explore the extracted logic at https://github.com/dvkndn/typed-tailwind/tree/master/convert :D
